baseURL = "https://adventure-northern-escapes.co.uk/"
relativeURLs = true
canonifyURLs = true
languageCode = 'en-us'
title = 'Adventure Northern'

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    name = "About Us"
    url = "/about/"
    weight = 20
  [[menu.main]]
    name = "Meet The Team"
    url = "/team/"
    weight = 30
 [[menu.main]]
  name = "Services"
  url = "/services/"
  weight = 40 # This will place it after "Meet The Team"

[[menu.main]]
  name = "Case Studies"
  url = "/case-studies/"
  weight = 50 # This will place it after "Services"


 [params]
  contact_email = "info@adventure-northern-escapes.co.uk"
  contact_phone = "+44 20 4592 1076"
  contact_address = "C/O Rodliffe Accounting, Level 37, 1 Canada Square, London, United Kingdom, E14 5AA"


[minify]
  minifyOutput = true

[minify.tdewolff]
  [minify.tdewolff.html]
    keepConditionalComments = true
    keepDefaultAttrVals = true
    keepDocumentTags = true
    keepEndTags = true
    keepQuotes = true
    keepWhitespace = false
  [minify.tdewolff.css]
    keepCSS2 = true
    precision = 0
  [minify.tdewolff.js]
    keepVarNames = false
    precision = 0
  [minify.tdewolff.json]
    precision = 0
  [minify.tdewolff.xml]
    keepWhitespace = false
